version: "3.9"

x-base-service: &base-service
  build:
    context: .
    dockerfile: docker/production.Dockerfile
  environment:
    - DATABASE_URL=psql://tta:tta123@db-product:5432/tracktraceapi
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq-product:5672//
  volumes:
    - .:/app
  depends_on:
    - db-product
    - rabbitmq-product
  restart: on-failure

services:
  db-product:
    image: postgres:14.1
    container_name: db-product
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=tracktraceapi
      - POSTGRES_USER=tta
      - POSTGRES_PASSWORD=tta123

  rabbitmq-product:
    image: rabbitmq:alpine
    container_name: rabbitmq-product
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django-product:
    <<: *base-service
    container_name: django-product
    command: ./docker/web_entrypoint.sh
    ports:
      - "8001:8000"

  celery-product:
    <<: *base-service
    container_name: worker-product
    command: ./docker/celery_entrypoint.sh

  beats-product:
    <<: *base-service
    container_name: beats-product
    command: ./docker/beats_entrypoint.sh
